FROM php:8.1-apache

# Instalar extensiones necesarias
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpng-dev libjpeg-dev libfreetype6-dev libzip-dev zip unzip git mariadb-client \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd mysqli pdo pdo_mysql zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Configurar permisos para Moodle
RUN mkdir -p /var/moodledata \
    && chown -R www-data:www-data /var/moodledata \
    && chmod -R 755 /var/moodledata

RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html
