FROM php:8.1-apache

# Instalar extensiones necesarias
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpng-dev libjpeg-dev libfreetype6-dev zip unzip git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd mysqli pdo pdo_mysql \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Configurar directorio de Moodle
COPY ./moodle /var/www/html/
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html
